apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wire-api-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: wire-api
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: upload-worker-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: upload-worker
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
