apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wire-project
  namespace: argocd
spec:
  description: "Enterprise Wire CLI-to-API Project"
  sourceRepos:
    - "*"
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
